from typing_extensions import Any, Iterable


class Error(Exception): ...
class Warning(Warning): ...
class InterfaceError(Error): ...
class DatabaseError(Error): ...
class DataError(DatabaseError): ...
class OperationalError(DatabaseError): ...
class IntegrityError(DatabaseError): ...
class InternalError(DatabaseError): ...
class ProgrammingError(DatabaseError): ...
class NotSupportedError(DatabaseError): ...
class PoolError(Error): ...

class Cursor:
    """MariaDB Cursor Object, used to execute statements and fetch results."""
    
    description: tuple[tuple[str, int, int, int, int, int, int], ...] | None
    rowcount: int
    
    def close(self) -> None: ...
    def execute(self, operation: str, params: tuple[Any, ...] | None = None) -> None: ...
    def executemany(self, operation: str, seq_of_params: Iterable[tuple[Any, ...]]) -> None: ...
    # NOTE: always use dictionary=True
    # def fetchone(self) -> tuple[Any, ...] | None: ...
    def fetchone(self) -> dict[str,Any] | None: ...
    def fetchmany(self, size: int | None = None) -> list[tuple[Any, ...]]: ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...
    def setinputsizes(self, sizes: Iterable[Any]) -> None: ...
    def setoutputsize(self, size: int, column: int | None = None) -> None: ...


class Connection:
    """MariaDB Connection Object, used to manage database sessions."""
    
    auto_reconnect: bool
    
    def cursor(self, *, cursorclass=Cursor|None,dictionary:bool|None) -> Cursor: ...
    def close(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def is_connected(self) -> bool: ...
    def get_server_info(self) -> str: ...
    def thread_id(self) -> int: ...


def connect(
    *,
    user: str | None = None,
    password: str | None = None,
    host: str | None = None,
    port: int | None = None,
    database: str | None = None,
    db: str | None = None,
    autocommit: bool = False,
    ssl: bool = False,
    pool_name: str | None = None,
    pool_size: int = 10,
    **kwargs: Any
) -> Connection:
    """
    Connects to the MariaDB database. Returns a Connection object.
    """
    ...

__all__ = [
    'connect',
    'Connection',
    'Cursor',
    'Error',
    'Warning',
    'InterfaceError',
    'DatabaseError',
    'DataError',
    'OperationalError',
    'IntegrityError',
    'InternalError',
    'ProgrammingError',
    'NotSupportedError',
    'PoolError',
]
